version: '3.0'

services:
  
  rasa_chatbot:
    env_file: 
      - ./.env
    build: .
    image: rasa-chatbot:latest
    ports:
      - 5005:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    command:
      - rasa
      - run
      - --enable-api
      - --model
      - /app/models
      - --endpoints
      - /app/config/endpoints.local.yml

  action_server:
    env_file: 
      - ./.env
    build: actions
    image: rasa-chatbot-actions:latest
    volumes:
      - ./actions:/app/actions
    command:
      - python3
      - -m
      - rasa_sdk
      - --actions
      - actions

